### ISSUE TITLE
Mínus tölur í veldisstreng í n bita floating point calc

### ISSUE THREAD

**Issue by HordurTryggvi** [ofurtumi/sjomli.github.io#3]
Hægt er að stilla stærð veldisstrengs sem neikvæða tölu, þá fer allt í rugl, UI og reikningar.

![kúkur](https://user-images.githubusercontent.com/97734972/191979431-9769d1ca-0bfc-4785-a91e-4942470c4cd0.PNG)

**Comment by ofurtumi** [comment]
# :( 
þetta verður lagað í næstu útgáfu, kemur eftir smá
