### ISSUE TITLE
Kommutölur í stærð veldisstrengs

### ISSUE THREAD

**Issue by HordurTryggvi** [ofurtumi/sjomli.github.io#4]
Hægt er að setja kommutölu sem stærð veldisstrengs í n bita floating point calc. UI og reikningar fara í rugl

![prump](https://user-images.githubusercontent.com/97734972/191981126-b6e23ea4-6ffe-43e3-9e81-8e7206b816c3.PNG)

**Comment by ofurtumi** [comment]
úbbosí kippi þessu í lag
