### ISSUE TITLE
Whitespace í stað bitatölu í floating point calc

### ISSUE THREAD

**Issue by HordurTryggvi** [ofurtumi/sjomli.github.io#5]
Hægt er að setja whitespace í stað bitatölu, skilar alltaf 0.
![piss](https://user-images.githubusercontent.com/97734972/191981495-7978fe4f-2b26-4a52-bf73-e8d46eefc173.PNG)

**Comment by ofurtumi** [comment]
haha, javascript að kinga yfir sig, komið fix í nýjustu útgáfu
ef maður kallar á 
```js
Number(" ")
```
í js þá fær maður 0 því það er falsy
